#mv Acetonitrile-MeOH.xyz           208_Acetonitrile-MeOH.xyz
#mv Acetonitrile-Peptide_N.xyz      209_Acetonitrile-Peptide_N.xyz
#mv Acetonitrile-Water.xyz          210_Acetonitrile-Water.xyz
#mv Dimethylamine-Acetate.xyz       211_Dimethylamine-Acetate.xyz
#mv Dimethylamine-PO4H2.xyz         212_Dimethylamine-PO4H2.xyz
#mv Dimethylamine-Peptide_N.xyz     213_Dimethylamine-Peptide_N.xyz
#mv Dimethylamine-Peptide_O.xyz     214_Dimethylamine-Peptide_O.xyz
#mv Dimethylamine-Water.xyz         215_Dimethylamine-Water.xyz
#mv Dimethylammonium-Acetate.xyz    216_Dimethylammonium-Acetate.xyz
#mv Dimethylammonium-PO4H2.xyz      217_Dimethylammonium-PO4H2.xyz
#mv Dimethylammonium-Water.xyz      218_Dimethylammonium-Water.xyz
#mv Isobutane-Benzene.xyz           219_Isobutane-Benzene.xyz
#mv Isobutane-Isobutane.xyz         220_Isobutane-Isobutane.xyz
#mv Isobutane-Uracil.xyz            221_Isobutane-Uracil.xyz
#mv Isobutane-Water.xyz             222_Isobutane-Water.xyz
#mv Trimethylamine-Acetate.xyz      223_Trimethylamine-Acetate.xyz
#mv Trimethylamine-PO4H2.xyz        224_Trimethylamine-PO4H2.xyz
#mv Trimethylamine-Peptide_N.xyz    225_Trimethylamine-Peptide_N.xyz
#mv Trimethylamine-Water.xyz        226_Trimethylamine-Water.xyz
#mv Trimethylammonium-PO4H2.xyz     227_Trimethylammonium-PO4H2.xyz
#mv Trimethylammonium-Peptide_O.xyz 228_Trimethylammonium-Peptide_O.xyz
#mv Trimethylammonium-Water.xyz     229_Trimethylammonium-Water.xyz
#mv SSI-007PHE-160CYS-1-dimer.xyz    230_MethylBenzene-Ethanethiol.xyz
#mv SSI-021PHE-260ILE-1-dimer.xyz    231_MethylBenzene-Ethane.xyz
#mv SSI-034PHE-069MET-1-dimer.xyz    232_MethylBenzene-DimethylSulfide.xyz
mv SSI-029PHE-103HIE-1-dimer.xyz   233_MethylBenzene-4_MethylImidazole.xyz
